### PR TITLE
updated README.md for new lol and some grammatical changes

### PR DESCRIPTION
**Pull request by VihagChaturvedi**
-Added link to instructions for getting wine-615
-Updated installation and running instructions for better clarity
-Fixed a few grammatical errors here and there

### CODE REVIEW

**Comment by nhubaotruong** [comment]
I don't think we'll need to get that custom wine-615 version, lutris just updated `lutris-ge-lol` that can start the game already

**Comment by VihagChaturvedi** [comment]
I don't think it has pushed for all distros yet.
Also, can you link me the GH for ```lutris-ge-lol```

Other than that, there are a few other changes in README.md

**Comment by nhubaotruong** [comment]
I don't have the link, but it's available in lutris -> `Manage runners` -> `Manage Versions`. You can just download from there.

The other changes looks good to me

**Comment by VihagChaturvedi** [comment]
Yeah i figured it out, LoL loads much faster than the older ```lutris-lol-5.5-2```, so thats great

I may push more changes with perhaps more screenshots in a bit, since I hurriedly made a PR before class

**Comment by nhubaotruong** [comment]
So can you fix this MR later or can I remove the wine-615 line and then merge now ?

**Comment by VihagChaturvedi** [comment]
Upto u tbh, u can remove the ```wine-615``` line

ig u can merge rn, i will make another MR when i am free and try to make more changes later.

Maybe I should include instructions for managing runners too as that may help in the future

**Comment by nhubaotruong** [comment]
Thanks, I'll merge it after lunch

**Comment by VihagChaturvedi** [comment]
alr cool

**Pull request merged**
